--EXCEPSIONES PERSONALIZADAS

SET SERVEROUTPUT ON;


DECLARE

    RAN NUMBER:=ROUND(DBMS_RANDOM.VALUE(1,3));
    
    ERROR1 EXCEPTION;
    ERROR2 EXCEPTION;
    ERROR3 EXCEPTION;

BEGIN
    
    CASE
        WHEN RAN =1 THEN
        RAISE ERROR1;
        
        WHEN RAN =2 THEN
        RAISE ERROR2;
        
        WHEN RAN = 3 THEN 
        RAISE ERROR3;
    
    END CASE;
    DBMS_OUTPUT.PUT_LINE('YO NO ME TENGO QUE EJECUTAR');
    
    EXCEPTION 
    
    WHEN ERROR1 THEN
    DBMS_OUTPUT.PUT_LINE('NO MANEJAMOS EL ERROR1');
    
    
    WHEN ERROR2 THEN
    DBMS_OUTPUT.PUT_LINE('NO MANEJAMOS EL ERROR2');
    
    WHEN ERROR3  THEN
    DBMS_OUTPUT.PUT_LINE('NO MANEJAMOS EL ERROR3');

END;
/