--CREACION DE PARAMETROS DE ENTRADA Y SALIDA


CREATE OR REPLACE PROCEDURE MENOR(X IN NUMBER,Y IN NUMBER,Z OUT NUMBER)--Z ES UN VARIABLE DE SALIDA Y LAS DEMAS DE ENTRADA
IS

BEGIN
    IF(X > Y) THEN
    Z:=Y;
    ELSE
    Z:=X;
    END IF;

END;
/