--TAREA DE CICLOS CON WHILE

--FACTORIAL

SET SERVEROUTPUT ON;

DECLARE
      
    NUMERO NUMBER := 4;
    FACTORIAL NUMBER:=1;

BEGIN

    WHILE NUMERO > 0 LOOP
    DBMS_OUTPUT.PUT(NUMERO||' X');
    FACTORIAL:=FACTORIAL * NUMERO;
    NUMERO:=NUMERO-1;
    END LOOP;
    DBMS_OUTPUT.put_line(' FACTORIAL :'||FACTORIAL);

END;
/