-- TAREA DE LA PARTE DE CICLOS 1

SET SERVEROUTPUT ON;


DECLARE

    TYPE NOTASARRAY IS VARRAY(4) OF NUMBER;
    NOTAS NOTASARRAY := NOTASARRAY(95,60,75,85);
    
    PROMEDIO NUMBER(6,2):=0;
    CONTADOR NUMBER:=0;

BEGIN
    <<PROMEDIO_FOR>>
    FOR CONTADOR IN 1..4 LOOP
          DBMS_OUTPUT.PUT_LINE('NOTA :'||NOTAS(CONTADOR));
         PROMEDIO:=NOTAS(CONTADOR)+PROMEDIO;
        
        END LOOP PROMEDIO_FOR;
        PROMEDIO :=(PROMEDIO/4);
        DBMS_OUTPUT.PUT_LINE('PROMEDIO  '||PROMEDIO);

END;
/