--TAREA NUMERO 2 DE EL CURSO DE PL/SQL

SET SERVEROUTPUT ON;


DECLARE

SUELDO_BASE NUMBER:=900;
SUELDO_TOTAL NUMBER;


BEGIN

    IF(SUELDO_BASE <= 600)THEN
    SUELDO_TOTAL:=SUELDO_BASE * 1.15;
    DBMS_OUTPUT.PUT_LINE('SUELDO MENOR DE 600  :'||SUELDO_TOTAL);
    END IF;
    
    IF(SUELDO_BASE BETWEEN 601 AND 950) THEN
    SUELDO_TOTAL:=SUELDO_BASE * 1.135;
    DBMS_OUTPUT.put_line('SUELDO MENOR QUE 950  :'||SUELDO_TOTAL);
    END IF;
    
    IF(SUELDO_BASE BETWEEN 951 AND 1400) THEN
    SUELDO_TOTAL:=SUELDO_BASE * 1.10;
    DBMS_OUTPUT.put_line('SUELDO MENOR QUE 1400   :'||SUELDO_TOTAL);
    END IF;
    
    IF(SUELDO_BASE >=1401)THEN
    SUELDO_TOTAL:=SUELDO_BASE * 1.05;
    DBMS_OUTPUT.put_line('SUELDO MAYOR QUE 1401  :'||SUELDO_TOTAL);
    END IF;

END;
/