--CREAR LA FUNCION DE LA TAREA DE FUNCIONES Y PROCEDIMIENTOS

CREATE OR REPLACE FUNCTION PROMEDIO_NOTAS
(NOTA1 IN NUMBER,NOTA2 IN NUMBER,NOTA3 IN NUMBER,NOTA4 IN NUMBER)
RETURN NUMBER
IS
    PROMEDIO NUMBER:=0;
BEGIN 
    
        PROMEDIO:=((NOTA1 + NOTA2 + NOTA3 + NOTA4)/4);
        RETURN PROMEDIO;
    
END;
/


--LLAMADO DE LA FUNCION
--SELECT A.*,PROMEDIO_NOTAS(NOTA1,NOTA2,NOTA3,NOTA4)AS "PROMEDIO" FROM NOTAS A;