--FUNCION PL DEFINICION DE FUNCIONES DENTRO DE UN PL


SET SERVEROUTPUT ON;

DECLARE

    SALARIO_PROMEDIO NUMBER :=0;
    --===================
    --INICION DE LA FUNCION
    --===================
    FUNCTION OBTENER_PROMEDIO
    RETURN NUMBER
    IS
    PROMEDIO NUMBER:=0;
    
    BEGIN
        
        SELECT AVG(SALARIO)INTO PROMEDIO FROM EMPLEADOS;
        RETURN PROMEDIO;
    
    END;--=============FIN FUNCION

BEGIN--FUNCION PL
    SALARIO_PROMEDIO:=OBTENER_PROMEDIO();
    DBMS_OUTPUT.put_line('EL SALARIO PROMEDIO ES : '||SALARIO_PROMEDIO);

END;--FIN DEL PL
/