

set SERVEROUTPUT ON;

DECLARE
NOMBRE NVARCHAR2(100) :='ALLAN';
APELLIDO NVARCHAR2(100):='SANCHEZ';
NOMBRECOMPLETO NVARCHAR2(200);

HOY DATE:=SYSDATE;
NOMBRE2 NVARCHAR2(100);
BEGIN
NOMBRECOMPLETO:=(NOMBRE||' '||APELLIDO);

--FUNCIONES DE TEXTO O VARIABLES STRING
DBMS_OUTPUT.PUT_LINE('LARGO :'||length(NOMBRE));
DBMS_OUTPUT.PUT_LINE('TRIM :'||TRIM(NOMBRE)||';');
DBMS_OUTPUT.PUT_LINE('MAYUSCULAS :'||UPPER(NOMBRE));
DBMS_OUTPUT.PUT_LINE('MINUSCULAS ;'||LOWER(NOMBRE));

NOMBRE:=TRIM(NOMBRE);

--DBMS_OUTPUT.PUT_LINE('CORTAR :'||SUBSTR(NOMBRE,1,3));
DBMS_OUTPUT.PUT_LINE('REMPLACAR :'||REPLACE(NOMBRE,'LL','YY'));

--FUNCIONES DE DATOS TIPO FECHA

DBMS_OUTPUT.PUT_LINE('HOY :'||HOY);
DBMS_OUTPUT.PUT_LINE('AGREGAR MES :'||ADD_MONTHS(HOY,2));
DBMS_OUTPUT.PUT_LINE('AGREFAR DIAS :'|| (HOY+2));

--TO_CHAR
DBMS_OUTPUT.PUT_LINE('DIA :'||TO_CHAR(HOY,'DD'));
DBMS_OUTPUT.PUT_LINE('DIA MES :'||TO_CHAR(HOY,'DD-MM'));
DBMS_OUTPUT.PUT_LINE('ANIO :'||TO_CHAR(HOY,'YYYY'));

--VALORE NULOS
DBMS_OUTPUT.PUT_LINE('NOMBRE2 :'||NVL(NOMBRE2,'SIN VALORES'));

END;
/