--FUNCION QUE CALCULA LA EDAD ACTUAL

CREATE OR REPLACE FUNCTION EDAD_ACTUAL (FECHANACI IN DATE)
RETURN NUMBER
IS
EDAD NUMBER(3):=0;

BEGIN

    EDAD:=TRUNC((TO_NUMBER(TO_CHAR(SYSDATE,'YYYYMMDD'))-TO_NUMBER(TO_CHAR(FECHANACI,'YYYYMMDD')))/10000);
    
    RETURN EDAD;
    
    EXCEPTION
    WHEN OTHERS THEN
    EDAD:=0;
    
    RETURN EDAD;

END;
/