-- registros definidos por usuarios

set SERVEROUTPUT ON;

DECLARE
    
    type CARRO IS RECORD(
        MARCA NVARCHAR2(100),
        COLOR NVARCHAR2(100),
        PUERTAS NUMBER
    );

    MAZDA CARRO;
    TOYOTA CARRO;
    --PRODEDIMIENTO PARA MOSTRAR LOS REGISTROS
    PROCEDURE IMPRIMIR_CARRO(CAR CARRO)
    IS
    BEGIN
    DBMS_OUTPUT.PUT_LINE('MARCA :'||CAR.MARCA);
    DBMS_OUTPUT.PUT_LINE('COLOR :'||CAR.COLOR);
    DBMS_OUTPUT.PUT_LINE('PUERTAS :'||CAR.PUERTAS);
    END;
    --FIN DEL PROCEDIMINETO

BEGIN
    
    MAZDA.MARCA:='MAZDA';
    MAZDA.COLOR:='BLUE';
    MAZDA.PUERTAS:=4;

    TOYOTA.MARCA:='TOYOTA';
    TOYOTA.COLOR:='RED';
    TOYOTA.PUERTAS:=2;
    
    IMPRIMIR_CARRO(MAZDA);
    
END;
/