
-- CONDICION CASE
-- LAS PALABRAS CLAVES SON CASE WHEN THEN ELSE

SET SERVEROUTPUT ON;

DECLARE
--SENTENCIA PARA GENRARA NUMEROS RANDOM
RAN NUMBER :=ROUND(DBMS_RANDOM.VALUE(0,5));


BEGIN
DBMS_OUTPUT.PUT_LINE(RAN);

    CASE
        WHEN RAN = 0 THEN
        DBMS_OUTPUT.PUT_LINE('CERO');
        WHEN RAN =1 THEN
        DBMS_OUTPUT.PUT_LINE('UNO');
        WHEN RAN =2 THEN
        DBMS_OUTPUT.PUT_LINE('DOS');
        WHEN RAN =3 THEN
        DBMS_OUTPUT.PUT_LINE('TRES');
        WHEN RAN =4 THEN 
        DBMS_OUTPUT.PUT_LINE('CUATRO');
        ELSE
        DBMS_OUTPUT.PUT_LINE('CINCO');
    END CASE;

END;
/