 -- IF ANIDADOS  SE USA LA PALABRA RESERVADA ESLIF
 
 SET SERVEROUTPUT ON;
 
 
 DECLARE
 --VARIABLES
 NOTA NUMBER :=50;
 
 BEGIN
 
    IF (NOTA >= 90) THEN
    DBMS_OUTPUT.PUT_LINE('EXELENTE');
    
    ELSIF (NOTA >= 80 ) THEN
    DBMS_OUTPUT.PUT_LINE('MUY BIEN');
    
    ELSIF(NOTA >= 70 )THEN
    DBMS_OUTPUT.PUT_LINE('BIEN');
    
    ELSE
    DBMS_OUTPUT.PUT_LINE('DEBE MEJORAR');
    
    END IF;
 
 END;
 /