SET SERVEROUTPUT ON;

DECLARE
--DECLARACION DE VARIABLES

SALARIO NUMBER := 1200;
NOMBRE NVARCHAR2(100);
ACTIVO BOOLEAN;
FECHA DATE;

BEGIN
NOMBRE :='ALLAN SANCHEZ';
FECHA := SYSDATE;
ACTIVO:=TRUE;

DBMS_OUTPUT.PUT_LINE('SALARIO :'||SALARIO);--SE CONCATENA CON EL || NOMBRE_VARIABLE
DBMS_OUTPUT.PUT_LINE('NOMBRE :'||NOMBRE);
DBMS_OUTPUT.PUT_LINE('FECHA : '||FECHA);
DBMS_OUTPUT.PUT_LINE('ACTIVO :'|| CASE WHEN ACTIVO THEN 'VERDADERO' ELSE 'FALSO'END );

END;
/
