
-- CURSORES EN TIEMPO DE EJECUCION

SET SERVEROUTPUT ON;



DECLARE
    
    PROMEDIO NUMBER:=0;

BEGIN
    
    <<CURSORES>>
    FOR FILA IN(SELECT * FROM NOTAS) LOOP
    PROMEDIO:=((FILA.NOTA1+FILA.NOTA2+FILA.NOTA3+FILA.NOTA4)/4);
    DBMS_OUTPUT.put_line('NOMBRE : '||FILA.NOMBRE||' PROMEDIO :'||PROMEDIO);
    END LOOP CURSORES;

END;
/